<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\node\NodeInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_page_attachments().
 *
 * @todo Need to optimize this later.
 */
function sms_sendtophone_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'sms_sendtophone/default';
}

/**
 * Implements hook_node_links_alter().
 */
function sms_sendtophone_node_links_alter(array &$links, NodeInterface $node, array &$context) {
  /** @var \Drupal\user\UserInterface $user */
  $user = User::load(\Drupal::currentUser()->id());
  $types = \Drupal::config('sms_sendtophone.settings')->get('content_types');
  $build = [];
  if (in_array($node->bundle(), $types)) {
    if ($user->hasPermission('send to any number') || (!empty($user->sms_user['number']) && $user->sms_user['status'] == 2)) {
      // Only show "send to phone" link if user is permitted to do so.
      $build['sms_sendtophone'] = array(
        'title' => t('Send to phone'),
        'url' => Url::fromRoute('sms_sendtophone.page', ['type' => 'node', 'extra' => $node->id()], ['query' => drupal_get_destination()]),
        'attributes' => array(
          'class' => 'sms-sendtophone',
          'title' => 'Send a link via SMS.',
        ),
      );
    }
    else if ($user->id() > 0) {
      // Show messages to encourage users to register their mobile number.
      if (empty($user->sms_user['number'])) {
        $build['sms_sendtophone'] = array(
          'title' => t('Setup your mobile number to send to phone.'),
          'url' => Url::fromRoute('sms_user.user_edit', ['user' => $user->id()]),
        );
      }
      elseif ($user->sms_user['status'] != 2) {
        $build['sms_sendtophone'] = array(
          'title' => t('Confirm your mobile number to send to phone.'),
          'url' => Url::fromRoute('sms_user.user_edit', ['user' => $user->id()]),
        );
      }
    }
    $links['sms_sendtophone'] = array(
      '#theme' => 'links__node__sms_sendtophone',
      '#links' => $build,
      '#attributes' => array('class' => array('links', 'inline')),
    );
  }
  // Add thickbox js if module exists.
  if (\Drupal::moduleHandler()->moduleExists('thickbox')) {
    $links['#attached']['library'][] = 'sms_sendtophone/thickbox_js';
  }

}

/**
 * Implements hook_form_alter().
 */
function sms_sendtophone_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if ($form_id == 'sms_sendtophone_inline_form' || $form_id == 'sms_sendtophone_node_form' || $form_id == 'sms_sendtophone_cck_form') {
    if (!\Drupal::currentUser()->hasPermission('send to any number')) {
      // Makes number field plain text.
      $form['sms']['number']['#type'] = 'item';
      $form['sms']['number']['#value'] = $form['sms']['number']['#default_value'];
    }
  }
}
