<?php
// $Id$

function sms_email_gateway_gateway_info() {
  
  return array(
    'email' => array(
      'name' => 'E-mail',
      'identifier' => 'email',
      'send_form' => 'sms_email_gateway_send_form',
      'send' => 'sms_email_gateway_send',
    ),
  );
}

/**
 * Returns custom additions to be added to the send forms
 */
function sms_email_gateway_send_form($destination = NULL, $required = TRUE) {  
  $options = array();
  if (!$required) {
    $options[0] = '<'. t('none') .'>';
  }
  
   $options += _sms_email_gateway_providers();
    
  $form['carrier'] = array(
    '#type' => 'select',
    '#title' => t('Carrier'),
    '#multiple' => FALSE,
    '#description' => t('Select your wireless carrier.'),
    '#options' => $options,
    '#default_value' => $destination->carrier,
    '#required' => $required,
  );
  
  return $form;
}

/**
 * Callback for sending messages.
 */
function sms_email_gateway_send($destinations, $message) {
  $from = variable_get('site_mail', ini_get('sendmail_from'));
  
  foreach ($destinations as $destination) {
    $to = $destination->number .'@'. $destination->carrier;
    drupal_mail('sms_email_gateway', $to, '', $message, $from);
  }
}

function _sms_email_gateway_providers() {
  return array(
    'msg.acsalaska.com' => t('Alaska Communications Systems'),
    'message.alltel.com' => t('Alltel Wireless'),
    'txt.att.net' => t('AT&T/Cingular'),
    'mobile.celloneusa.com' => t('CellularOne'),
    'cwemail.com' => t('Centennial Wireless'),
    'messaging.sprintpcs.com' => t('Helio'),
    'page.nextel.com' => t('Nextel'),
    'qwestmp.com' => t('Qwest'),
    'messaging.sprintpcs.com' => t('Sprint'),
    'tmomail.net' => t('T-Mobile'),
    'vmobl.com' => t('Virgin Mobile'),
    'vtext.com' => t('Verizon'),
  );
}