include:
  - project: $_GITLAB_TEMPLATES_REPO
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

variables:
  OPT_IN_TEST_NEXT_MAJOR: '1'
  OPT_IN_TEST_NEXT_MINOR: '1'
  SKIP_ESLINT: '1'
  _CURL_TEMPLATES_REF: 'main'
  _TARGET_PHP: "8.3"
  _CSPELL_IGNORE_PATHS: '"Makefile"'

.myComposerJob:
  extends: .composer-base
  after_script:
    # Bring the dependency into non-dev since the compiler pass is intelligent
    # about whether a service should be conditionally registered if it's a
    # dev dependency (via `ContainerBuilder::willBeAvailable`)
    # 'no-interaction' answers yes to the move from --dev
    - composer require symfony/fake-sms-notifier --no-interaction

composer:
  extends: .myComposerJob

composer (next minor):
  extends: .myComposerJob
