<?php

/**
 * @file
 * Install, update and uninstall functions for SMS Framework.
 */

declare(strict_types=1);

use Drupal\sms\Direction;

/**
 * Implements hook_requirements().
 *
 * @phpstan-return array<string, array{title: \Drupal\Core\StringTranslation\TranslatableMarkup, severity: int, value: \Drupal\Core\StringTranslation\TranslatableMarkup}>
 */
function sms_requirements(string $phase): array {
  $requirements = [];

  if ($phase === 'runtime') {
    $base_query = \Drupal::entityTypeManager()
      ->getStorage('sms')
      ->getQuery()
      ->accessCheck(FALSE);

    $query = clone $base_query;
    $count = $query
      ->condition('queued', 0)
      ->condition('direction', Direction::INCOMING)
      ->condition('processed', NULL, 'IS NULL')
      ->count()
      ->execute();

    $requirements['sms_queue_incoming'] = [
      'title' => t('SMS incoming queue'),
      'severity' => \REQUIREMENT_INFO,
      'value' => \Drupal::translation()->formatPlural(
        $count,
        'There are @count messages in the incoming queue.',
        'There are @count messages in the incoming queue.',
      ),
    ];

    $query = clone $base_query;
    $count = $query
      ->condition('queued', 0)
      ->condition('direction', Direction::OUTGOING)
      ->condition('processed', NULL, 'IS NULL')
      ->count()
      ->execute();

    $requirements['sms_queue_outgoing'] = [
      'title' => t('SMS outgoing queue'),
      'severity' => \REQUIREMENT_INFO,
      'value' => \Drupal::translation()->formatPlural(
        $count,
        'There are @count messages in the outgoing queue.',
        'There are @count messages in the outgoing queue.',
      ),
    ];
  }

  return $requirements;
}

/**
 * Implements hook_update_last_removed().
 */
function sms_last_update_last_removed(): int {
  return 8101;
}
