<?php
// $Id$

/**
 * Implementation of hook_menu().
 */
function smsframework_devel_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    $items[] = array(
      'path' => 'admin/settings/smsframework/smsframework_devel',
      'title' => t('Developer tools'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('smsframework_devel_send_form'),
      'access' => user_access('administer smsframework_devel'),
      'type' => MENU_NORMAL_ITEM,
    );
  }

  return $items;
}

function smsframework_devel_send_form() {
  $form['destination_number'] = array(
    '#type' => 'textfield',
    '#title' => t('Destination Address'),
    '#description' => t('A full mobile number in international format. A US number would be 11 didgets with the country code. (Example: 15555555)'),
    '#size' => 40,
    '#maxlength' => 255,
  );
  
  $form['message'] = array(
    '#type' => 'textarea',
    '#title' => t('Message'),
    '#cols' => 60,
    '#rows' => 5,
  );
  
  $form['submit'] = array(
    '#type' => 'submit', 
    '#value' => t('Send'),
  );
  
  return $form;
}

function smsframework_devel_send_form_submit($form_id, $form_values) {
  smsframework_send($form_values['destination_number'], $form_values['message']);
  drupal_set_message(t('Your message was sent through the API.'));
}

function smsframework_devel_smsframework_info() {
  $options['email_address'] = array(
    '#type' => 'textfield',
    '#title' => t('Destination e-mail address'),
    '#description' => t('Messages will be sent to this e-mail address.'),
    '#required' => TRUE,
    '#size' => 40,
    '#maxlength' => 255,
  );
  
  
  return array(
    'email_dev' => array(
      'name' => 'E-mail Only (for development)',
      'identifier' => 'email_dev',
      'options' => $options,
      'send' => 'smsframework_devel_send',
    ),
  );
}

function smsframework_devel_send($destination, $message, $mid) {
  $gateway = smsframework_gateways('gateway', 'email');
  // dprint_r($gateway);
  drupal_mail('smsframework-devel-send', $gateway['configuration']['email_address'], t('Test message from SMS Framework'), $message);
}