<?php

// $Id$

function sms_email_gateway_uninstall() {
  // TODO: leaving these here for now, in case we need it.
  // variable_del('sms_email_gateway_sendmail_path');
  // variable_del('sms_email_gateway_mail_user');
  // variable_del('sms_email_gateway_mail_domain');
  variable_del('sms_email_gateway_enable_node_id');
  variable_del('sms_email_gateway_enable_user_id');
  variable_del('sms_email_gateway_enable_username');
}