<?php
// @codingStandardsIgnoreFile
/**
 * @file
 * A database agnostic dump for testing purposes.
 *
 * This file was generated by the Drupal 8.0 db-tools.php script.
 */

use Drupal\Core\Database\Database;

$connection = Database::getConnection();
$custom_message = 'This is a custom confirmation message from [site:name]. Confirmation code: [confirm:code]';

$connection->insert('variable')
  ->fields(['name', 'value'])
  ->values(['sms_user_confirmation_message', serialize($custom_message)])
  ->execute();
