# Schema for the configuration files of the SMS User module.

sms_user.settings:
  type: config_object
  label: 'SMS User settings'
  mapping:
    registration_form:
      type: integer
      label: 'Show mobile fields during user registration'
    confirmation_message:
      type: string
      label: 'Confirmation message format'
    active_hours:
      type: mapping
      mapping:
        status:
          type: boolean
          label: 'Enable sleep hours'
        ranges:
          type: sequence
          sequence:
            - type: mapping
              mapping:
                start:
                  type: string
                  label: 'Start time in PHP strtotime natural language.'
                end:
                  type: string
                  label: 'End time in PHP strtotime natural language.'
    account_registration:
      type: mapping
      mapping:
        all_unknown_numbers:
          type: mapping
          mapping:
            status:
              type: boolean
              label: 'Enable all_unknown_numbers'
            reply:
              type: mapping
              mapping:
                status:
                  type: boolean
                  label: 'Enable reply message'
                message:
                  type: string
                  label: 'Reply message'
        formatted:
          type: mapping
          mapping:
            status:
              type: boolean
              label: 'Enable formatted'
            incoming_messages:
              type: sequence
              label: 'incoming_messages'
              sequence:
               - type: string
                 label: 'incoming_message'
            activation_email:
              type: boolean
              label: 'Activation email'
            reply:
              type: mapping
              mapping:
                status:
                  type: boolean
                  label: 'Enable reply message'
                message:
                  type: string
                  label: 'Reply message'
