<?php

/**
 * @file
 * Allows bulk text messages to be sent to registered users.
 */

/**
 * Implements of hook_permission().
 */
function sms_blast_permission() {
  return array(
    'Send SMS Blast' => array(
      'title' => t('Send SMS Blast'),
      'description' => t('This allows the user to send an SMS blast.'),
    ),
  );
}

/**
 * Implements of hook_menu().
 */
function sms_blast_menu() {
  $items['sms_blast'] = array(
    'title'            => 'SMS Blast',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('sms_blast_form'),
    'access arguments' => array('Send SMS Blast'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Display the sms blast form
 */
function sms_blast_form() {
  $form['message'] = array(
    '#type' => 'textarea',
    '#title' => t('Message'),
    '#cols' => 60,
    '#rows' => 5,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Send'),
  );

  return $form;
}

/**
 * Submit handler for the sms blast form
 */
function sms_blast_form_submit(&$form, $form_state) {
  $result = db_query("SELECT uid FROM {sms_user} WHERE status = 2");

  if ($result->rowCount() != 0) {
    foreach ($result as $row) {
      sms_user_send($row->uid, $form_state['values']['message']);
    }
    drupal_set_message(t('The message was sent to %count users.', array('%count' => $result->rowCount())));
  }
  else {
    drupal_set_message(t('There are 0 users with confirmed phone numbers. The message was not sent.'));
  }
}