<?php

/**
 * @file
 * Provides integration between the SMS Framework and Drupal users.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\sms\Entity\SmsMessageInterface as SmsMessageEntityInterface;
use Drupal\sms\Message\SmsMessageInterface;

/**
 * Implements hook_entity_presave().
 */
function sms_user_entity_presave(EntityInterface $entity) {
  // Delay sending SMS message if active hours are enabled.
  if ($entity instanceof SmsMessageEntityInterface) {
    /** @var \Drupal\sms_user\ActiveHoursInterface $active_hours */
    $active_hours = \Drupal::service('sms_user.active_hours');
    $active_hours->delaySmsMessage($entity);
  }
}

/**
 * Implements hook_sms_incoming().
 */
function sms_user_sms_incoming($op, SmsMessageInterface $sms_message, array $options) {
  if ($op == 'pre process') {
    /** @var \Drupal\sms_user\AccountRegistrationInterface $account_registration */
    $account_registration = \Drupal::service('sms_user.account_registration');
    $account_registration->createAccount($sms_message);
  }
}
