<?php

/**
 * @file
 * A test gateway to be used for testing the sms framework
 */
use Drupal\sms\Message\SmsMessageInterface;

/**
 * Implements hook_sms_incoming().
 */
function sms_test_gateway_sms_incoming_preprocess(SmsMessageInterface $sms_message) {
  // Save incoming result for later retrieval.
  $key = 'sms_test_gateway_sms_incoming_preprocess';
  $result = &drupal_static($key);

  if (!is_null($sms_message->getRecipients()) && !is_null($sms_message->getMessage())) {
    $result['number'] = $sms_message->getRecipients()[0];
    $result['message'] = $sms_message->getMessage();
    \Drupal::state()->set($key, $result);
  }
}

function sms_test_gateway_get_incoming($reset = FALSE) {
  $key = 'sms_test_gateway_sms_incoming_preprocess';
  $result = &drupal_static($key);

  if (!isset($result)) {
    $result = \Drupal::state()->get($key, array());
  }

  if ($reset) {
    \Drupal::state()->delete($key);
    drupal_static_reset($key);
  }
  return $result;
}
