<?php

/**
 * @file
 * A test gateway to be used for testing the SMS Framework.
 */

declare(strict_types=1);

use Drupal\sms_test_gateway\EventSubscriber\SmsTestGatewayEventSubscriber;

/**
 * Gets incoming data from static.
 */
function sms_test_gateway_get_incoming($reset = FALSE): ?array {
  /** @var array|null $result */
  $result = &drupal_static(SmsTestGatewayEventSubscriber::STATE_SMS_INCOMING_PREPROCESS);

  if ($result === NULL) {
    $result = \Drupal::state()->get(SmsTestGatewayEventSubscriber::STATE_SMS_INCOMING_PREPROCESS, []);
  }

  if ($reset === TRUE) {
    \Drupal::state()->delete(SmsTestGatewayEventSubscriber::STATE_SMS_INCOMING_PREPROCESS);
    drupal_static_reset(SmsTestGatewayEventSubscriber::STATE_SMS_INCOMING_PREPROCESS);
  }
  return $result;
}
