<?php

/**
 * Implements hook_sms_incoming_preprocess().
 */
function sms_test_sms_incoming_preprocess(\Drupal\sms\Message\SmsMessageInterface $sms_message) {
  \Drupal::state()->set(__FUNCTION__, TRUE);
}

/**
 * Implements hook_sms_incoming_postprocess().
 */
function sms_test_sms_incoming_postprocess(\Drupal\sms\Message\SmsMessageInterface $sms_message) {
  \Drupal::state()->set(__FUNCTION__, TRUE);
}